name: life_os
description: A secure, modular, local-first Life Companion application.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^13.1.0

  # UI
  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.2

  # Database (Foundation for later)
  path_provider: ^2.1.2
  intl: ^0.20.2
  fl_chart: ^1.1.1
  table_calendar: ^3.2.0
  shared_preferences: ^2.5.4
  supabase_flutter: ^2.12.0
  flex_color_scheme: ^8.4.0
  google_fonts: ^6.3.3
  url_launcher: ^6.3.2
  http: ^1.6.0
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.2.1
  syncfusion_flutter_pdf: ^32.1.21
  file_picker: ^10.3.8
  home_widget: ^0.7.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  upgrader: ^11.3.0
  signature: ^5.5.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  
  # Code Generation
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9

# Configuration flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/icon.png"
  # Options Android
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/icon.png"
  # Options iOS
  remove_alpha_ios: true

flutter:
  uses-material-design: true